<?php // AUTO-GENERATED BY GRUNT. To change this block edit Gruntfile.js, not this file! ?>

<script src="<?php echo get_template_directory_uri(); ?>/_ui/js/app.main.js"></script>
<script src="<?php echo get_template_directory_uri(); ?>/_ui/js/components/app.component.js"></script>
