<?php // AUTO-GENERATED BY GRUNT. To change this block edit Gruntfile.js, not this file! ?>

<script src="<?php echo get_template_directory_uri(); ?>/_ui/js/head-libs/jquery-1.11.1.min.js"></script>
<script src="<?php echo get_template_directory_uri(); ?>/_ui/js/head-libs/modernizr-dev.js"></script>
